### ISSUE TITLE
Does not work with Django 1.10

### ISSUE THREAD

**Issue by douglas** [deschler/django-modeltranslation#381]
Hello,

I was testing if I can use Django 1.10 in a project I'm working right now, but seems that the removal of ._defered attribute in Django 1.10 broke django-modeltranslation.

I tried to see if it was a quick fix but seems you rely a lot on deferred fields so I'm not the best person to fix it =( 

Here is my traceback:

```python
» python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10a54c378>
Traceback (most recent call last):
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/modeltranslation/models.py", line 81, in handle_translation_registrations
    autodiscover()
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/modeltranslation/models.py", line 32, in autodiscover
    import_module(module)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Volumes/DADOS/Work/sandbox/enjbrasil/fuji/apps/commons/translation.py", line 6, in <module>
    class CountryTranslationOptions(TranslationOptions):
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/modeltranslation/decorators.py", line 23, in wrapper
    translator.register(model_or_iterable, opts_class, **options)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/modeltranslation/translator.py", line 427, in register
    opts = self._get_options_for_model(model, opts_class, **options)
  File "/Volumes/DADOS/Work/ambientes/fuji/lib/python3.5/site-packages/modeltranslation/translator.py", line 547, in _get_options_for_model
    if model._deferred:
AttributeError: type object 'Country' has no attribute '_deferred'
```

Any ideas?

Thanks for your project, it's amazing =)

**Comment by raratiru** [comment]
Same issue +1.

I have just upgraded to Django 1.10, and I immediately downgraded.

**Comment by zlorf** [comment]
I'll take a look in following days.

**Comment by allcaps** [comment]
From the release notes:

> The Model._deferred attribute is removed as dynamic model classes when using QuerySet.defer() and only() is removed.

https://docs.djangoproject.com/en/1.10/releases/1.10/

**Comment by zlorf** [comment]
Progress info: I've managed to get test running, yet some are failing.
Modeltranslation relies heavily on Django's internal API, which tends to change in new releases. That's the case this time as well. Not only deferred models are the problem now.

**Comment by zlorf** [comment]
I'm currently on a 10-day holiday trip; I've pushed what I've done so far to a new branch (`master-dj110-integration`)- whoever feels like helping, you can take this as a base for further integration.

**Comment by SalahAdDin** [comment]
Progress info please.

**Comment by maparent** [comment]
Having a look. In new_refresh_from_db, after the append_translated, you would also want to add a append_fallback; we get infinite recursion otherwise.

**Comment by zlorf** [comment]
Progress info: most of the issues were resolved. Only `autodiscover` test is failing, but it's not surprising since lots of hacking happens there.

**Comment by SalahAdDin** [comment]
Thank you very much!

**Comment by zlorf** [comment]
All test are passing on all Django versions.
Probably I still need to add one more test and fix two recent issues, so by the end of the week a Django 1.10-compatible version will be released.

**Comment by zlorf** [comment]
Ok, master branch should be Django 1.10 compatible.
Whoever want to contribute to testing, you can install it by invoking `pip install https://github.com/deschler/django-modeltranslation/archive/master.zip`. Please report here any issues found, that are not covered by tests.

**Comment by matthiask** [comment]
I've just tested this with a Django site of medium complexity and it works fine! Thanks.

**Comment by karamanolev** [comment]
I migrated a Django 1.10 project from having no i18n to using django-modeltranslation and I've seen no issues so far. I'm only using basic functionality though.

**Comment by karamanolev** [comment]
@zlorf Do you have immediate plans to release a version of django-modeltranslation on pypi that supports Django 1.10? Right now I'm using the one from master, but we'd rather install it from pypi. Thanks a lot for fixing the issues.

**Comment by zlorf** [comment]
@karamanolev Yes I do. However I don't want to release an untested version, so that's why I'm waiting for some more feedback.

**Comment by karamanolev** [comment]
Thanks a lot for the info. Looking forward.

**Comment by allcaps** [comment]
I've installed modeltranslation master branch in my project and updated Django from 1.9.6 to 1.10. 

I needed to fix some Django 1.10 specific stuff (not modeltranslation related). After that modeltranslation registered 6 models for translation with 1-4 fields per model using 4 languages. 

I ran all my tests. All green. Then I dropped and recreated the db. All good. Finally build many fixtures without problems.

@zlorf: Thanks for the good work. Modeltranslation works like a charm.

**Comment by zlorf** [comment]
So it seems that everything works.
@deschler Could you publish a new release? I just need to add one remark to the README.

**Comment by deschler** [comment]
@zlorf Sure, just let me know when you're done. And once more thanks for the great job! :)

**Comment by hymnis** [comment]
Running Django 1.10 with Python 2.7 and just installed modeltranslation from master using pip. Created and populated translation.py and as this project already has tables and data I ran:
`python manage.py sync_translation_fields`
which resulted in:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/management/commands/sync_translation_fields.py", line 49, in <module>
    class Command(BaseCommand):
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/management/commands/sync_translation_fields.py", line 54, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

Guessing this stems from the fact that the use of "option_list" has been deprecated since version 1.8 and now removed. Overriding "add_arguments()" seems to be the way to add custom arguments. See [this](https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#django.core.management.BaseCommand.option_list) part of the Django documentation.

Or am I alone in manifesting this error?

**Comment by zlorf** [comment]
@hymnis Thanks, this is important. I need to fix this before release.

**Comment by karamanolev** [comment]
My impression was that ever since Django got official in-trunk migration support, sync_translation_fields should not longer be used and migrations used instead. I'm only running update_translation_fields and it works OK on Django 1.10. Is that somehow wrong?

**Comment by hymnis** [comment]
@zlorf Np, glad I could help.

@karamanolev so you just use "python manage.py syncdb" and "python manage.py update_translation_fields" instead?
Or do you manage to only use update_translation_fields somehow? Just for kicks, I tried, but as expected it failed as the the columns it tries to update doesn't exist.

**Comment by karamanolev** [comment]
@hymnis Yes, that's the workflow that I'm using.

**Comment by hymnis** [comment]
@karamanolev Thanks for pointing that out. That route seems to work for me as well (so far).

**Comment by primoz-k** [comment]
Hi @zlorf !
Please check #383

**Comment by manikos** [comment]
Should I or not use the current release of `django-modeltranslation` for my current Django project?

**Comment by matthiask** [comment]
@manikos Why shouldn't you?

@zlorf @deschler Is there anything missing for a Django 1.10-supporting release? No failing builds on [Travis CI](https://travis-ci.org/deschler/django-modeltranslation/) anymore, might be a good time for a release?

**Comment by deschler** [comment]
Looks good to me. @zlorf just wanted to add something to the readme. And since he did all the hard work, i'm waiting for his okay. :)

**Comment by zlorf** [comment]
Yeah, I've forgot. Will modify README in a moment.

**Comment by zlorf** [comment]
@deschler , what was the command for building docs? ;)

**Comment by zlorf** [comment]
Yep. That's what I tried, but in the wrong folder. Got it now.

**Comment by zlorf** [comment]
Ok @deschler , docs updated. The code is ready for you to make release ritual!
(after putting a lot of entries to changelog ;P )

**Comment by deschler** [comment]
Made the release yesterday. Closing here. Thanks everyone!
