### ISSUE TITLE
NullCharField.to_python retun None 

### ISSUE THREAD

**Issue by POD666** [deschler/django-modeltranslation#400]
I have trouble working with URLFields. 
When I pass empty string URLField.clean(u"") method raising exception:
'NoneType' object has no attribute 'strip'

Looks like the bug is here:
https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/forms.py#L20
Working with Django 1.8.17:
https://github.com/django/django/blob/d3d12fc11da56e4ea8af37a22a9a0aa6579ab2d5/django/forms/fields.py#L748

Any advices?

**Comment by POD666** [comment]
Providing empty_values = {'url': ''} to TranslationOptions fixed issue.
