### ISSUE TITLE
Django 5 support?

### ISSUE THREAD

**Issue by Mapiarz** [deschler/django-modeltranslation#719]
Is Django 5.0 supported, officially or not? Anybody tried it?

**Comment by last-partizan** [comment]
Haven't tried personally, but it should work.

If you interested - you can fork the repo, see if test suite passes on django 5, and make a PR enabling it in the pipeline. (Maybe fixing some bugs along the way)

**Comment by last-partizan** [comment]
I tried it, and it does not work.

**Comment by philitell** [comment]
Please support Django 5 - that would be really great.

Thanks for this great project!!!

**Comment by koleror** [comment]
Why do you say it doesn't work? I personnally use it with django 5.0.3 and it works just fine

**Comment by philitell** [comment]
I tested it with Django 5.0.4 and Django-Restframework 3.15.1 --> package works perfectly

Thanks for this great project!!!

**Comment by last-partizan** [comment]
> Why do you say it doesn't work? I personnally use it with django 5.0.3 and it works just fine

Test suite was not passing. If it works in general, it's great news. But please be aware - you can still catch some bugs, until we add django-5.0 to our test matrix and all checks are passed.

**Comment by hovi** [comment]
What doesn't work for me is django admin frontend (no tabs). This is chrome console output:
```
TypeError: tabsContainer.tabs is not a function
    createTabs http://localhost:8000/static/modeltranslation/js/tabbed_translation_fields.js:259
    each jQuery
    createTabs http://localhost:8000/static/modeltranslation/js/tabbed_translation_fields.js:209
    <anonymous> http://localhost:8000/static/modeltranslation/js/tabbed_translation_fields.js:525
    jQuery 13
```

**Comment by last-partizan** [comment]
Now we're testing against django 5.0, and it works.

**Comment by ateuber** [comment]
Unfortunately it is not working with Django 5.1
```
  File "/usr/local/lib/python3.11/site-packages/modeltranslation/fields.py", line 221, in __init__
    elif self.remote_field and not self.remote_field.is_hidden():
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToOneRel' object has no attribute 'is_hidden'. Did you mean: 'hidden'?
```

**Comment by last-partizan** [comment]
Tried to fix this in #756, but it's slightly more complicated than that.

You can investigate why tests are failing in `django-5.1` branch and create PR targeting that branch with a fixes. Or i will look into this when i have more time.

**Comment by last-partizan** [comment]
@ateuber Please, check if your project works with `django-5.1` branch.

If everything is okay, I'll merge it in somewhere next week.

**Comment by ateuber** [comment]
@last-partizan The error is gone, thank you! :+1:
