### ISSUE TITLE
Full Support for Django 1.11 and Django 2.0

### ISSUE THREAD

**Issue by raratiru** [deschler/django-modeltranslation#436]
Django 2.0 is [about to be released](https://code.djangoproject.com/wiki/Version2.0Roadmap#schedule).

From Django 1.8, modeltranslation does not seem to follow [Django's progress](https://github.com/deschler/django-modeltranslation/issues/375).

WIll modeltranslation follow? 

Since it is a core application in our project we need some time to schedule a refactoring in our code if it is going to cease upgrading for some reason.

**Comment by pypetey** [comment]
+1

**Comment by ramonakira** [comment]
We would like support for Django 1.11 as well since we're using it in a few of our sites.

**Comment by elohmeier** [comment]
After upgrading to Django 2.0 I receive this error when running unit tests:

```
(venv) enno@nw1 ~/Development/slx/slx8123_MenuService (django2) $ python manage.py test
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/management/commands/test.py", line 59, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/test/runner.py", line 548, in setup_databases
    self.parallel, **kwargs
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/test/utils.py", line 176, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 76, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 119, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/core/serializers/base.py", line 80, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 115, in get_objects
    queryset = model._default_manager.using(self.connection.alias).order_by(model._meta.pk.name)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1083, in using
    clone = self._chain()
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1156, in _chain
    obj = self._clone()
  File "/Users/enno/Development/slx/slx8123_MenuService/venv/lib/python3.6/site-packages/modeltranslation/manager.py", line 213, in _clone
    return super(MultilingualQuerySet, self)._clone(**kwargs)
TypeError: _clone() got an unexpected keyword argument '_rewrite'
```

I've registered translations using the TranslationOptions base class and registered a TranslationAdmin.

**Comment by AlexejStukov** [comment]
The problem seems to be that `clone` was reworked [in Django 2.0](https://github.com/django/django/commit/6155bc4a51d44afa096c4c00766cbfb9ba9d660c).

**Comment by aoviedo92** [comment]
the same error but with _populate
`return super(MultilingualQuerySet, self)._clone(**kwargs)
      TypeError: _clone() got an unexpected keyword argument '_populate'`

**Comment by aoviedo92** [comment]
the same error, but with `_populate`

`
return super(MultilingualQuerySet, self)._clone(**kwargs)
TypeError: _clone() got an unexpected keyword argument '_rewrite'
`

**Comment by davesque** [comment]
I'm having the same issue with exceptions being raised during unit tests with Django 2.0.

**Comment by davesque** [comment]
I spent some time last Friday looking into fixing this but it was a little difficult to see where to start.  Does anyone more familiar with the library have any advice on what specifically needs to be updated?

**Comment by sky-code** [comment]
@davesque all usage of Query.clone need to be updated

**Comment by davesque** [comment]
@sky-code Sure, but when you check out master and try to run tox, the tests appear to fail for other reasons.  It seems that some import magic which tries to delay loading models isn't working.  There were some other issues as well.

**Comment by decibyte** [comment]
Hi all. I'm working on [2.0 support for `django-audit-log`](https://github.com/Atomidata/django-audit-log/issues/52) and have run into the same problem there. I'll follow you here hoping to get a solution from you. And will of course share it if I find the answer myself :)

**Comment by zlorf** [comment]
@decibyte What is the exception? `django-audit-log` doesn't depend on `modeltranslation`, does it?

**Comment by decibyte** [comment]
@zlorf, nope, see my updated comment :) It's all happening in a project I have, utilising both 3rd party packages. I got confused because DAT has a very broad exception catching in a place, which also catches this error from MT.

They do though affect each other in a way, because they both mess around with the same things deep inside Django.

**Comment by Nihisil** [comment]
I guess Django 2.0 brought a lot of changes and this package will not be easy to upgrade. 

This is answer about Djanto 2.0 support from similar package maintainer: https://github.com/KristianOellegaard/django-hvad/issues/344#issuecomment-348620367

**Comment by raratiru** [comment]
@Nihisil That's good news. 

According to [@spectras](https://github.com/spectras), ([No 1 collaborator](https://github.com/KristianOellegaard/django-hvad/graphs/contributors) of [django-hvad](https://github.com/KristianOellegaard/django-hvad)),  `hvad2` **is** compatible with Django 2.0 and currently under [active development](https://github.com/KristianOellegaard/django-hvad/issues/344#issuecomment-348620367)!

This sounds like an alternative in the sad case django-modeltranslation ceases developing.

**Comment by dmarcelino** [comment]
> Nonetheless, Django 1.11 is an LTS Release.

I'd like to highlight this statement. Django 1.10 will see it's extended support end this month while 1.11's extended support will last until April 2020. Supporting 1.11 is certainly an important milestone and I hope django-modeltranslation gets there.

**Comment by rcatajar** [comment]
>  Supporting 1.11 is certainly an important milestone and I hope django-modeltranslation gets there.

I'm using django-modeltranslation with 1.11 and I have never noticed any issue. Do you know if there's a list of known issues somewhere ?

**Comment by Nihisil** [comment]
> I'm using django-modeltranslation with 1.11 and I have never noticed any issue. Do you know if there's a list of known issues somewhere ?

You can't use new Manager methods like `.chain()` or `.append()` with modeltranslation, because they are not implemented.

**Comment by raratiru** [comment]
@rcatajar Some issues are listed in #375 which dates from June 2016.

**Comment by raratiru** [comment]
@rcatajar Some issues are listed in #375 which dates from June 2016.

There is also a pull request #398 for this issue which dates from December 27 2016 and is neglected for some reason.

**Comment by karolyi** [comment]
+1

**Comment by abdolhosein** [comment]
I've patched this issue and now is working! Just wait for application of pull request.

**Comment by abdolhosein** [comment]
@elohmeier 
@Nihisil 
@karolyi 
@sky-code 
@davesque 

My patch code **is now passed** all the tests **except** those related to django 1.8. If anybody likes to do work with this module could utilize my forked repository instead of current version of this repo, till I fix django 1.8 related issues and push(send a pull request) them here.

let others know **;)**

Have a good fun.

**Comment by karolyi** [comment]
@deschler, can we get this fixed?

**Comment by irvined1982** [comment]
Thanks for the patch @abdolhosein - working well with 2.0 for me.

**Comment by munisisazade** [comment]
Thank you @abdolhosein also works for me with Django 2.0 :)

**Comment by lokkomokko** [comment]
@abdolhosein  Yes! Thank you so much!

**Comment by Aesirry** [comment]
@abdolhosein the patch works great! Wondering when it will be merged

**Comment by deschler** [comment]
Sorry guys, hardly got time to work on modeltranslation these days.

The patch looks good. I think we can ignore the Django 1.8 failure. In fact we should consider to drop support for anything older than Django 1.11.

**Comment by raratiru** [comment]
Thank you!

**Comment by dmarcelino** [comment]
Hi @deschler, welcome back!

I agree with you but perhaps we can do a final release for folks stranded on django <=1.10? I suggest doing a `0.12.2` release from commit 00fc7f1804aaa1b1e37af48e67871080851e14b0, which includes PR #431, and a `0.13` release from master whenever you feel it's ready.

**Comment by raratiru** [comment]
Indeed a great idea, a new release that can -at least- be compatible with django-1.11 LTS. That would also close #448 & #450 .

**Comment by deschler** [comment]
@dmarcelino Released 0.12.2 as suggested.
Thanks everyone for your help and patience!

**Comment by sikmir** [comment]
@deschler Something wrong with 0.12.2 release, because there are no merged changes. Moreover there is no 0.12.2 tag.

**Comment by karolyi** [comment]
@sikmir I have 0.12.2 installed in my venv.

**Comment by deschler** [comment]
@sikmir I can confirm that the 0.12.2 tag was missing (created now), but PR #431 is in the release as far as i can tell.

**Comment by sikmir** [comment]
@deschler I see, I've just missed that 0.12.2 does not include django 2.0 support (#447). So need to wait for 0.13:)

**Comment by discoroveryx** [comment]
hi, how get 0.13 release for django 2.0? Version 0.12 raise "_clone() got an unexpected keyword argument '_rewrite'"

**Comment by hugodes** [comment]
@deschler When can we expect Django 2.0 support ? In 1.13 ? If so when do you think this could be ?

Cheers,

**Comment by dmarcelino** [comment]
> @dmarcelino Released 0.12.2 as suggested.

> @sikmir I can confirm that the 0.12.2 tag was missing (created now), but PR #431 is in the release as far as i can tell.

Hi @deschler, I've installed `0.12.2` and so far everything looks good. 👍 I've also checked the pypi package and the changes from PR #431 are there indeed. Thanks!

**Comment by deschler** [comment]
I've been asked if i could need a helping hand to get a release with Django 2.0 done. There are indeed a few things to speed it up:

- Make the tests work with Django 2.0
- Fix issues that pop up once the tests work
- See if the docs need update for Django 2.0
- Remove special version handling for anything older than Django 1.11 (modeltranslation 0.13 will support Django 1.11 and 2.0)

**Comment by PetrDlouhy** [comment]
Hi, I might be confused, but I think, that the support for `Django 2.0` isn't fully implemented yet. There are two problems:

1. The version `0.12.2` isn't compatible with `Django 2.0`. There must be some mistake in creating that version, because the `master` branch works.
2. The tests fails. I tried to fix the testing in #451, but there are still two left unresolved tests.

**Comment by deschler** [comment]
0.12.2 is compatible with Django 1.11.
0.13 will be compatible with Django 1.11 and Django 2.0.

**Comment by discoroveryx** [comment]
How install 0.13 via pip ?
pip install django-modeltranslation
version: 0.12.2

**Comment by sikmir** [comment]
@discoroveryx 0.13 is not released yet.

> 0.13 **will** be compatible with Django 1.11 and Django 2.0.

**Comment by Dulcin** [comment]
Looking forward to 0.13, I'm facing the same issue.

**Comment by Dulcin** [comment]
@discoroveryx You can install the latest with:
pip install git+https://github.com/deschler/django-modeltranslation.git

**Comment by naderalexan** [comment]
@Dulcin is it possible to specify release with this syntax? e.g. pip install git+https://github.com/deschler/django-modeltranslation.git**==0.13b**

**Comment by sunmoon11** [comment]
When dose 0.13 release?

**Comment by jeffersonlizar** [comment]
I installed patch-the-issue-with-django2 refered by @munisisazade and so far it has worked well for me

**Comment by dmarcelino** [comment]
Looking at the latest `django-modeltranslation` build ([link](https://travis-ci.org/deschler/django-modeltranslation/jobs/335590954)) there are still 2 test failures:

```
FAIL: test_reverse_relations (modeltranslation.tests.tests.OneToOneFieldsTest)
FAIL: test_select_related (modeltranslation.tests.tests.TestManager)
```

That's likely what's holding a new release. Unfortunately there doesn't seem to be any open PRs to address those.

**Comment by Aesirry** [comment]
still getting the same error even with version 0.12.2:
```
Exception Value: _clone() got an unexpected keyword argument '_rewrite'
```
when using the fix by @abdolhosein it worked, but now it won't deploy my app on heroku

**Comment by raratiru** [comment]
#457 Is an open issue asking for an ETA on a new model-translation release.

**Comment by ziima** [comment]
Any news on 0.13?

**Comment by karolyi** [comment]
why is this issue closed when it's not released yet?

**Comment by kakulukia** [comment]
please release!

**Comment by dmarcelino** [comment]
For those who have not subscribed #457 deschler has now released `0.13-beta1` with support for Django 2.0 (https://github.com/deschler/django-modeltranslation/issues/457#issuecomment-381596104).

**Comment by urievenchen** [comment]
> 0.12.2 is compatible with Django 1.11.
> 0.13 will be compatible with Django 1.11 and Django 2.0.

The requirements table at http://django-modeltranslation.readthedocs.io/en/latest/installation.html doesn't mention 0.12.2 for Django 1.11.

**Comment by karolyi** [comment]
#467 shows that the module is still not fully compatible with django 2.x.

**Comment by urievenchen** [comment]
> @urievenchen The lines quoted in your post are from January!

Then it's time to fix this bug!

https://github.com/deschler/django-modeltranslation/issues/460

**Comment by OrufbekM** [comment]
this doesn't work for me and from django.utils.six import with_metaclass it gives this error: ModuleNotFoundError: No module named 'django.utils.six' 

pls help me

**Comment by last-partizan** [comment]
Hello. This is old issue about Django 2.0 which is unsupported at the moment.

We now target at least Django 4.2, and neither we nor Django use `six` anymore.

**Comment by OrufbekM** [comment]
What to do?

**Comment by OrufbekM** [comment]
![Image](https://github.com/user-attachments/assets/afcada1f-3a0b-4cf4-920e-6a8bf20e9e7b)

**Comment by last-partizan** [comment]
Update django and django-modeltranslation to the latest versions.

If issue persists, create a new Issue and provide repository with reproduction.

Specify:

django version
modeltranslation version

**Comment by OrufbekM** [comment]
Thank you for your help.
